config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  devise_for :users
  get 'home/index'
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord
  mount_uploader :submission_image, SubmissionImageUploader
  mount_uploader :submission_video, SubmissionVideoUploader

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :submissions
        
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]

  # GET /submissions
  # GET /submissions.json
  def index
    @submissions = Submission.all
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
    @submission = current_user.submissions.build
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = current_user.submissions.build(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:title, :body, :url, :submission_image, :submission_video)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_svg(name, styles: "fill-current text-gray-400", title:nil)
    filename = "#{name}.svg"
    title ||= name.underscore.humanize
    inline_svg(filename, aria: true, nocomment: true, title: title, class: styles)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<%= render_svg 'icons/edit', styles: "fill-current text-purple-500 w-4 h4" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=IBM+Plex+Sans:400,400i,500,600,700' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-200 relative h-screen overflow-x-hidden">
  <% flash.each do |type, message| %>
    <% if type == "alert" %>
    <div class=".bg-red-500">
      <div class= "container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
        <%= message %>
      </div>
    </div>
    <% end %>

    <% if type == "notice" %>
    <div class=".bg-green-500">
      <div class= "container px-2 mx-auto py-4 text-white text-center font-medium font-sans">
        <%= message %>
      </div>
    </div>
    <% end %>
  <% end %>

  <nav class="bg-white py-2 border-b border-gray-400" role="navigation" aria-label="main navigation">
    <div class=".flex.flex-wrap items-center justify-center lg:justify-start lg:content-center [ px-4 lg:px-6">

      <%= link_to root_path, class: "leading-normal no-underline text-gray-800 my-2 md:my-0" do %>
        <h1 class="text-lg pr-2 font-bold">FORUM</h1>
        <% end %>

        <div class="flex flex-wrap justify-start w-full lg:w-2/3">
          <div class="w-full lg:w-1/4 px-0 md:px-2 mb-2 lg:mb-0">
              <div class="relative">
                <select class="select" id="community">
                  <option>Community 1</option>
                  <option>Community 2</option>
                  <option>Community 3</option>
                </select>
                <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                  <%= render_svg 'icons/chevron-down' %>
                </div>
              </div>
          </div>
        

          <div class="w-full lg:w-1/2 px-0 md:px-2">
            <div class="relative">
              <input class="input pl-10" id="search" type="text" placeholder="Search Forum" />
              <div class="pointer-events-none absolute inset-y-0 left-0 flex items center px-3 text-gray-700">
              <%= render_svg 'icons/chevron-down', styles: "fill-current h-4 w-4" %>
              </div>
            </div>
          </div>
        </div>

        <div class=".w-full flex flex-wrap flex-1 items-center justify-end pt-4 lg:pt-0">
          <div class="mr-3">
            

            <% if user_signed_in? %>
              <%= link_to new_submission_path do %>
                <%= render_svg "icons/create" %>
              <% end %>
              <% else %>
              <%= link_to "Login", new_user_session_path, class: "btn btn-outline btn-small mr-2" %>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline btn-small mr-2" %>
            <% end %> 
          </div>

          <% if user_signed_in? %>
                <div class="dropdown rounded bg-white border border-gray-400 text-gray-600 ml-1 hover:bg-gray-200">
                  <div class="dropdown-content pt-2 pb-2 pl-3 pr-1">
                    <%= link_to "#", class: "js-dropdown-user-target no-underline flex justify-between text-gray-700 uppercase text-xs tracking-wide items-center font-semibold" do %>
                    <%= current_user.username if current_user.username %>
                    <%= render_svg "icons/chevron-down" %>
                    <% end %>

                    <ul class="list-none hidden dropdown-list absolute left-o rounded-b border border-gray-500 shadow">
                    <h5 class="mt-2 uppercase text-xs text-gray-500 font-normal py-2 pl-3 tracking-wide">My Stuff</h5>

                    <li>
                      <%= link_to "#", class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 flex items-center text-sm" do %>
                      <%= render_svg "icons/user", styles: "icons-md fill-current text-gray-600 mr-3" %> My Profile
                      <% end %>
                    </li>
                    <li>
                      <%= link_to edit_user_registration_path, class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 flex items-center text-sm" do %>
                      <%= render_svg "icons/settings", styles: "icons-md fill-current text-gray-600 mr-3" %> Account Settings
                      <% end %>
                    </li>
                    <li>
                      <%= link_to destroy_user_session_path, class: "hover:bg-purple-500 hover:text-white text-gray-700 no-underline block py-2 px-4 flex items-center text-sm" do %>
                      <%= render_svg "icons/signout", styles: "icons-md fill-current text-gray-600 mr-3" %> Sign Out
                      <% end %>
                    </li>
                    </ul>

                  </div>
                </div>
          <% end %>
        </div>
    </div>
  </nav>
  

    <%= yield %>

  </body>
</html>

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
        <% submission.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :submission_image %>
    <%= form.file_field :submission_image %>
  </div>

  <div class="field">
  <%= form.label :submission_video %>
  <%= form.file_field :submission_video %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.title %></td>
        <td><%= submission.body %></td>
        <td><%= submission.url %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @submission.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @submission.body %>
</p>

<p>
  <strong>Url:</strong>
  <%= @submission.url %>
</p>

#<%= debug(@submission.submission_image.large.url) %>

<p>
<strong>Submission Image:</strong>
<%= image_tag @submission.submission_image.large.url, width: 400 %>
</p>

<p>
<strong>Video:</strong>
<%# @submission.submission_video %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>